### ISSUE TITLE
Mitigation Request Feature

### ISSUE THREAD

**Issue by christiankiller** [blockchain-signaling-system/bloss-core#1]
## Intro
This feature _enables_ one of the **main** features of `bloss-dashboard`. 
It should interrupt the control flow of `bloss-core`'s automatic mitigation and request mitigation from the parties.
This happens in several steps: 
1. As soon as attackers are retrieved (see here [..manager.py](https://github.com/blockchain-signaling-system/bloss-core/blob/master/bloss/manager.py#L31))
2. There should be an interruption before posting to the ['ENDPOINT']['STALK']. 
3. This interruption sends the attack_report to `bloss-node` which relays the attack_report via Websocket to the `bloss-dashboard`. 
_More steps to be added_ 

## TODO
**The mitigation request feature should** 
- [ ] ... ~enable the "pausing" of the mitigation until there is feedback of the frontend (`bloss-dashboard`_answers via Websockets to_ `bloss-node` which then posts to `bloss-core` which will resume the mitigation.~ 
- [x] ... send POST to `bloss-node` (containing all the details regarding attack reports)
- [ ] ... ~send individual attack-reports only once via POST. As of now it's reported multiple times.~

**Comment by christiankiller** [comment]
Directly calling stalk API /mitigate/ from `bloss-node`.
No additional logic implemented on bloss-core side, since it only increases complexity and doesn't bring any benefits.
